### PR TITLE
IRONN-130-Spain-v5-all-orgs

### PR DESCRIPTION
**Pull request by mcjustin**
1. Moves "Instituto Valenciano de Oncologia" (146-146) to v5 effective 2020-10-21T23:00:00Z . This will need a dry-run @pbugni .
2. Switches "Hospital Universitario Miguel Servet (Zaragoza)" (146-180) to v5, effective for all time (this was a new site added March '22 - they accidentally asked for v3 at that time).
3. Removes a redundant org config for "Hospital Universitario Virgen de la Victoria". The removed config is at v3, which is incorrect. The remaining config has the valid transition to v5; this config was later in the file, and it appears that it overrode the prior/bad config, fortunately (at least, as I read https://eproms.truenth.org/api/organization?tree_view=true today).

https://jira.movember.com/browse/IRONN-130

### CODE REVIEW

**Comment by pbugni** [comment]
1. Can of worms.  Lots of patients which had previously completed v3 work, will end up with QuestionnaireResponses that do NOT map to v5.  For example, Patient 3735 (170-146-002), or Patient 3734 (170-146-001):
```
Patient 3734 (170-146-001):
	Modified QNRs (old, new)
		qnr 40047 ['IRONMAN_v3_recurring_annual_pattern', 0] ==> ['IRONMAN_v5_recurring_3mo_pattern', 2]
		qnr 40048 ['IRONMAN_v3_recurring_annual_pattern', 0] ==> ['none of the above', None]
		qnr 40049 ['IRONMAN_v3_recurring_annual_pattern', 0] ==> ['none of the above', None]
		qnr 40050 ['IRONMAN_v3_recurring_annual_pattern', 0] ==> ['none of the above', None]
		qnr 40051 ['IRONMAN_v3_recurring_annual_pattern', 0] ==> ['none of the above', None]
		qnr 59506 ['IRONMAN_v3_recurring_annual_pattern', 1] ==> ['IRONMAN_v5_recurring_annual_pattern', 1]
		qnr 59507 ['IRONMAN_v3_recurring_annual_pattern', 1] ==> ['none of the above', None]
		qnr 59508 ['IRONMAN_v3_recurring_annual_pattern', 1] ==> ['IRONMAN_v5_recurring_annual_pattern', 1]
		qnr 59509 ['IRONMAN_v3_recurring_annual_pattern', 1] ==> ['IRONMAN_v5_recurring_annual_pattern', 1]
		qnr 59510 ['IRONMAN_v3_recurring_annual_pattern', 1] ==> ['IRONMAN_v5_recurring_annual_pattern', 1]
```
2. We can't just retroactively alter the protocol, as 5 patients have timeline data in v3.  Furthermore, similar problems to the previous case, for example on patients 5685, 5687, 5724, and 5725. 
3. Thank you for removing the duplicate entry for 146103 - I concur that it already had the correct values.

**Comment by mcjustin** [comment]
@pbugni  are you able to quantify (without too much work) the level of impact, i.e., what proportion (numerator and denominator would be good to) of total QR's would be abandoned with this change for each site? They'll want to know that...

**Comment by mcjustin** [comment]
```
* We do report QR's in the data reports even if they don't align with a QB, I believe - can you please confirm?
```
Actually, as I review a QR CSV report from Sept '22, all of the records have `timepoint` populated with a QB - darn. They'll want confirmation of this, please do check.

**Comment by pbugni** [comment]
@mcjustin after fighting with the complications of a query for such numerator / denominator values as you requested, opted to extend the code so we can see this summary after each `preview-site-update` run.  anything else you need in this?

for #1 (site 146-146):
```
Total QuestionnaireResponses for all affected patients in organization: 164
  Number of those QNRs completed before RP change: 164
  Number of those QNRs completed after RP change: 144
```

for #2 (site 146-180, and again, we MUST retired the v3, can't just insert v5):
```
Total QuestionnaireResponses for all affected patients in organization: 52
  Number of those QNRs completed before RP change: 52
  Number of those QNRs completed after RP change: 38
```

**Comment by mcjustin** [comment]
@pbugni  my other question was: do we include QR's in the CSV data reports even if they don't align with a QB?

> @mcjustin after fighting with the complications of a query for such numerator / denominator values as you requested, opted to extend the code so we can see this summary after each `preview-site-update` run. anything else you need in this?
...
>
@pbugni  , along with:
`Total QuestionnaireResponses for all affected patients in organization`
 it would be good to know:
`Total QuestionnaireResponses for all patients in organization`
`Number of affected patients in organization`
`Number of patients in organization`

**Comment by pbugni** [comment]
The one thing this doesn't capture, which might be nice, is to know the number of questionnaire BANKS with altered status (i.e. the number that were completed that are now partial or expired).  Bit more work, but reasonable if you want that?

Here's the current summary report for each:

```
164 QuestionnaireResponses for all patients in organization 146146
Instituto Valenciano de Oncologia
  Patients in organization: 31
  Patients negatively affected by change: 12
  Number of those QNRs assigned to a QB before RP change: 164
  Number of those QNRs assigned to a QB after RP change: 144
```

```
52 QuestionnaireResponses for all patients in organization 146180
Hospital Universitario Miguel Servet (Zaragoza)
  Patients in organization: 5
  Patients negatively affected by change: 5
  Number of those QNRs assigned to a QB before RP change: 52
  Number of those QNRs assigned to a QB after RP change: 38
  ```

**Comment by pbugni** [comment]
Now including QB effects:

```
164 QuestionnaireResponses for all patients in organization 146146
Instituto Valenciano de Oncologia
  Patients in organization: 31
  Patients negatively affected by change: 12
  Number of those QNRs assigned to a QB before RP change: 164
  Number of those QNRs assigned to a QB after RP change: 144
  Number of QuestionnaireBanks completed before RP change: 37
  Number of QuestionnaireBanks completed after RP change: 20
```

```
52 QuestionnaireResponses for all patients in organization 146180
Hospital Universitario Miguel Servet (Zaragoza)
  Patients in organization: 5
  Patients negatively affected by change: 5
  Number of those QNRs assigned to a QB before RP change: 52
  Number of those QNRs assigned to a QB after RP change: 38
  Number of QuestionnaireBanks completed before RP change: 14
  Number of QuestionnaireBanks completed after RP change: 0
  ```

**Comment by pbugni** [comment]
@mcjustin, I've confirmed there are no other duplicates in the `Organization.json` file for eproms:

```
(eproms3) bradly-2 bash ~/uw/truenth-portal 0$  grep '"id":' portal/config/eproms/Organization.json | sort > sorted.master
(eproms3) bradly-2 bash ~/uw/truenth-portal 0$  grep '"id":' portal/config/eproms/Organization.json | sort -u > sorted.unique.master
(eproms3) bradly-2 bash ~/uw/truenth-portal 0$  diff sorted.master sorted.unique.master 
22d21
<       "id": 146103,
```

and double checked, no such duplicates in this branch.

**Comment by mcjustin** [comment]
@pbugni  I talked w/ PCCTC about this today. Since the Spanish sites are "all paper", I think they're okay with re-entering the ~40 questionnaires that would be displaced by this v5 change, since they'll gain the proper v5 questionnaire data in the process. But it would be nice to provide them a list of affected patients, QB's and questionnaires, like you provided in the post above https://github.com/uwcirg/truenth-portal/pull/4279#issuecomment-1366993695 
, so they wouldn't need to hunt and peck for what needed re-entry (looking at the current adherence report, they already have a lot of 'Expired' timepoints, so the new 'Expired' timepoints would be hard to find) namely:

```
Patient 3734 (170-146-001):
	Modified QNRs (old, new)
		qnr 40047 ['IRONMAN_v3_recurring_annual_pattern', 0] ==> ['IRONMAN_v5_recurring_3mo_pattern', 2]
		qnr 40048 ['IRONMAN_v3_recurring_annual_pattern', 0] ==> ['none of the above', None]
		qnr 40049 ['IRONMAN_v3_recurring_annual_pattern', 0] ==> ['none of the above', None]
		qnr 40050 ['IRONMAN_v3_recurring_annual_pattern', 0] ==> ['none of the above', None]
		qnr 40051 ['IRONMAN_v3_recurring_annual_pattern', 0] ==> ['none of the above', None]
		qnr 59506 ['IRONMAN_v3_recurring_annual_pattern', 1] ==> ['IRONMAN_v5_recurring_annual_pattern', 1]
		qnr 59507 ['IRONMAN_v3_recurring_annual_pattern', 1] ==> ['none of the above', None]
		qnr 59508 ['IRONMAN_v3_recurring_annual_pattern', 1] ==> ['IRONMAN_v5_recurring_annual_pattern', 1]
		qnr 59509 ['IRONMAN_v3_recurring_annual_pattern', 1] ==> ['IRONMAN_v5_recurring_annual_pattern', 1]
		qnr 59510 ['IRONMAN_v3_recurring_annual_pattern', 1] ==> ['IRONMAN_v5_recurring_annual_pattern', 1]
```
How much work to do that?

**Comment by mcjustin** [comment]
Well... re my commit just now:
```
Switches these two Spanish orgs' v3 retired_as_of date to this coming Monday;
    PCCTC wants this interim state, as once we have the list of affected patients
    and timepoints for the change going farther back, they'll still need to
    discuss w/ the Spanish sites to see what's tolerable there. So this interim
    step allows for collection of future PROs according to v5.
```
https://github.com/uwcirg/truenth-portal/pull/4279/commits/48d63bc243bdb5fa78abcec25f75560d833609f8

**Review by ivan-c — APPROVED** [review]

**Comment by pbugni** [comment]
@mcjustin here are the long awaited details - naming the visit and questionnaire needing reentry for each respective patient:

```
 Details of patients having lost a QuestionnaireResponse association:
  Patient 3733
    visit: Month 3 questionnaire: ironmisc
    visit: Month 6 questionnaire: ironmisc
  Patient 5881
    visit: Baseline questionnaire: ironmisc
  Patient 5783
    visit: Baseline questionnaire: ironmisc
  Patient 5711
    visit: Baseline questionnaire: ironmisc
  Patient 5534
    visit: Baseline questionnaire: ironmisc
  Patient 5481
    visit: Baseline questionnaire: ironmisc
    visit: Month 9 questionnaire: ironmisc
  Patient 5302
    visit: Baseline questionnaire: ironmisc
    visit: Month 3 questionnaire: ironmisc
  Patient 5270
    visit: Month 3 questionnaire: ironmisc
  Patient 4983
    visit: Month 6 questionnaire: ironmisc
    visit: Month 15 questionnaire: ironmisc
  Patient 4229
    visit: Month 9 questionnaire: ironmisc
    visit: Month 21 questionnaire: ironmisc
  Patient 3936
    visit: Month 24 questionnaire: ironmisc
  Patient 3734
    visit: Month 12 questionnaire: ironmisc
    visit: Month 12 questionnaire: factfpsi
    visit: Month 12 questionnaire: epic26
    visit: Month 12 questionnaire: prems
    visit: Month 24 questionnaire: ironmisc
  Patient 3735
    visit: Month 12 questionnaire: ironmisc
    visit: Month 24 questionnaire: ironmisc
```

**Comment by mcjustin** [comment]
> @mcjustin here are the long awaited details - naming the visit and questionnaire needing reentry for each respective patient:
> 

@pbugni  thanks, that makes sense. During the meeting earlier today I said that I wasn't certain, but that was based on a notification from github that excluded part of what you wrote there. I've let Marie know via https://jira.movember.com/browse/IRONN-130 , we'll see what they want to do.

**Pull request merged**
