### PR TITLE
TN-3205 new CLI `update-qnr` to manually correct a QNR

### PR DESCRIPTION
**Pull request by pbugni**
example use follows.  to view current value for a requested linkId within the given QuestionnaireResponse.id, include the `--noop` flag:

```
$  flask update-qnr --qnr_id 19490 --link_id irondemog_v3.27 --actor pbugni@gmail.com --noop
'{"text": "Are you Hispanic or Latino?", "answer": [{"valueString": "No"}, {"valueCoding": {"code": "irondemog_v3.27.2", "system": "https://eproms.truenth.org/api/codings/assessment"}}], "linkId": "irondemog_v3.27"}'
```

scrape and edit the above result, and include with the `--replacement` flag, to update the record:

```
$ flask update-qnr --qnr_id 19490 --link_id irondemog_v3.27 --actor pbugni@gmail.com --replacement 
'{"text": "Are you Hispanic or Latino?", "answer": [{"valueString": "Yes"}, {"valueCoding": {"code": "irondemog_v3.27.1", "system": "https://eproms.truenth.org/api/codings/assessment"}}], "linkId": "irondemog_v3.27"}'
```

finally, an example w/o a current answer:

```
$ flask update-qnr --qnr_id 16960 --link_id irondemog_v3.27 --actor pbugni@gmail.com --noop
'{"text": "Are you Hispanic or Latino?", "answer": [], "linkId": "irondemog_v3.27"}'

$  flask update-qnr --qnr_id 16960 --link_id irondemog_v3.27 --actor pbugni@gmail.com --replacement '{"text": "Are you Hispanic or Latino?", "answer": [{"valueString": "No"}, {"valueCoding": {"code": "irondemog_v3.27.2", "system": "https://eproms.truenth.org/api/codings/assessment"}}], "linkId": "irondemog_v3.27"}'
Updated QNR 16960 irondemog_v3.27 answer from [] to [{'valueString': 'No'}, {'valueCoding': {'code': 'irondemog_v3.27.2', 'system': 'https://eproms.truenth.org/api/codings/assessment'}}]
```

### CODE REVIEW

**Comment by mcjustin** [comment]
> example use follows. to view current value for a requested linkId within the given QuestionnaireResponse.id, include the `--noop` flag:
> 
> ```
> $  flask update-qnr --qnr_id 19490 --link_id irondemog_v3.27 --actor pbugni@gmail.com --noop
> '{"text": "Are you Hispanic or Latino?", "answer": [{"valueString": "No"}, {"valueCoding": {"code": "irondemog_v3.27.2", "system": "https://eproms.truenth.org/api/codings/assessment"}}], "linkId": "irondemog_v3.27"}'
> ```
> 
> scrape and edit the above result, and include with the `--replacement` flag, to update the record:
> 
> ```
> $ flask update-qnr --qnr_id 19490 --link_id irondemog_v3.27 --actor pbugni@gmail.com --replacement 
> '{"text": "Are you Hispanic or Latino?", "answer": [{"valueString": "Yes"}, {"valueCoding": {"code": "irondemog_v3.27.2", "system": "https://eproms.truenth.org/api/codings/assessment"}}], "linkId": "irondemog_v3.27"}'
> ```

Thanks @pbugni , a couple things:
1. In your example you're changing the valueString from "No" to "Yes", but you should also change the valueCoding.code from "irondemog_v3.27.2" to "irondemog_v3.27.1". 
2. In some cases we'll also need to add a response where there isn't one already (assuming the QR exists). Does this handle that scenario?

**Comment by pbugni** [comment]
@mcjustin At the moment, it's on us to edit both the `valueString` and `valueCoding` and no logic to confirm they match.  Not sure how to implement that short of bringing in the Questionnaire - is this suggested, or is it adequate to leave that on the user?  (I'll correct the example run)

As for adding a response where there isn't one - it's currently validating the question text match, I'll test we can insert where a previous answer doesn't exist.

**Comment by mcjustin** [comment]
> @mcjustin At the moment, it's on us to edit both the `valueString` and `valueCoding` and no logic to confirm they match. Not sure how to implement that short of bringing in the Questionnaire - is this suggested, or is it adequate to leave that on the user? (I'll correct the example run)
> 
> As for adding a response where there isn't one - it's currently validating the question text match, I'll test we can insert where a previous answer doesn't exist.

Sounds like a fine approach, thanks @pbugni

**Review by ivan-c — APPROVED** [review]

**Review by mcjustin — APPROVED** [review]
Approving, but I'll need to test on 'test'

**Pull request merged**
