### PR TITLE
Bugfix/empro expired UI

### PR DESCRIPTION
**Pull request by achen2401**
https://movember.atlassian.net/browse/TN-3250
frontend changes - accounting for when EMPRO questionnaire has expired.
**Note** - the frontend now will display the link to the EMPRO report if it detects that the user had completed EMPRO previously.
Example screenshot (user completed at least one EMPRO questionnaire previously):
emproCompleted

### CODE REVIEW

**Comment by mcjustin** [comment]
> https://movember.atlassian.net/browse/TN-3250 frontend changes - accounting for when EMPRO questionnaire has expired. Example screenshot: MainDueEmproExpired

@achen2401 What does the lower right box show when the user *has* completed a questionnaire and they are beyond the 12 months of EMPRO data collection?

**Review by pbugni — APPROVED** [review]
Nice solution, thank you.

**Comment by achen2401** [comment]
> @achen2401 What does the lower right box show when the user _has_ completed a questionnaire and they are beyond the 12 months of EMPRO data collection?

@mcjustin sorry, but I don't currently have such a patient in my instance but I just tried it out in Test, as that part of the code for the UI has not been changed by this current PR.  This is what the lower right corner card will looks like to the patient:
Screen Shot 2023-09-26 at 11 38 25 AM

**Comment by mcjustin** [comment]
> > @achen2401 What does the lower right box show when the user _has_ completed a questionnaire and they are beyond the 12 months of EMPRO data collection?
> 
> @mcjustin sorry, but I don't currently have such a patient in my instance but I just tried it out in Test, as that part of the code for the UI has not been changed by this current PR. This is what the lower right corner card will looks like to the patient: Screen Shot 2023-09-26 at 11 38 25 AM

Hmm, that looks incorrect for a patient who has completed at least one EMPRO questionnaire, and is beyond the 12 months. I know you didn't introduce the problem, but this seems like a good time to get it right...

**Comment by achen2401** [comment]
@mcjustin JUST FYI, I made the fix and updated the screenshot in the description after incorporating Paul's latest change to include `substudy_assessment_status.at_least_one_completed`info. Here is the updated screenshot again:
emproCompleted

**Comment by mcjustin** [comment]
@achen2401  sounds like this matches what's in our new spec/table at [2023-09-26 End of study states to consider and their effect on the UI](https://docs.google.com/document/d/12bYE6A1DZlURH9HoXgGnsLv4cV-Lo2lhjz6s7_6xHrg/edit#heading=h.3xy7telsorr5) . I see you still have it in draft, I'll keep an eye out for a review request.

**Comment by achen2401** [comment]
@mcjustin the PR should be ready for review now.

**Review by mcjustin — APPROVED** [review]

**Pull request merged**
