### PR TITLE
IRONN-197 Brooklyn on EMPRO

### PR DESCRIPTION
**Pull request by mcjustin**
https://jira.movember.com/browse/IRONN-197

### CODE REVIEW

**Comment by ivan-c** [comment]
@mcjustin can you rebase/merge this PR against master? 

Just merged a fix for the failing tests (#4325)

**Review by ivan-c — CHANGES_REQUESTED** [review]
@mcjustin can you rebase/merge this PR against master?

Just merged a fix for the failing tests (https://github.com/uwcirg/truenth-portal/pull/4325)

**Comment by mcjustin** [comment]
@ivan-c  I've rebased from master just now

**Review by ivan-c — APPROVED** [review]
Looks good, thanks!!

**Pull request merged**
